void test()
{
//=========Macro generated from canvas: FinalSpectrum/FinalSpectrum
//=========  (Wed Jul 22 22:15:32 2020) by ROOT version 6.16/00
   TCanvas *FinalSpectrum = new TCanvas("FinalSpectrum", "FinalSpectrum",0,27,1920,1025);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   FinalSpectrum->SetHighLightColor(2);
   FinalSpectrum->Range(0,0,1,1);
   FinalSpectrum->SetFillColor(0);
   FinalSpectrum->SetBorderMode(0);
   FinalSpectrum->SetBorderSize(2);
   FinalSpectrum->SetTickx(1);
   FinalSpectrum->SetTicky(1);
   FinalSpectrum->SetLeftMargin(0.12);
   FinalSpectrum->SetRightMargin(0.04);
   FinalSpectrum->SetTopMargin(0.04);
   FinalSpectrum->SetBottomMargin(0.14);
   FinalSpectrum->SetFrameLineColor(0);
   FinalSpectrum->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.5,0.545,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-4.878049,0.1,50,10.4125);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetLeftMargin(0.18);
   pad0->SetRightMargin(0);
   pad0->SetTopMargin(0.04);
   pad0->SetBottomMargin(0);
   pad0->SetFrameLineColor(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameLineColor(0);
   pad0->SetFrameBorderMode(0);
   Double_t xAxis1[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder0__1 = new TH1D("placeholder0__1","Central Values",8, xAxis1);
   placeholder0__1->SetMinimum(0.1);
   placeholder0__1->SetMaximum(10);
   placeholder0__1->SetStats(0);
   placeholder0__1->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder0__1->GetXaxis()->SetLabelFont(43);
   placeholder0__1->GetXaxis()->SetLabelSize(0.035);
   placeholder0__1->GetXaxis()->SetTitleSize(0.035);
   placeholder0__1->GetXaxis()->SetTitleOffset(0.8);
   placeholder0__1->GetXaxis()->SetTitleFont(42);
   placeholder0__1->GetYaxis()->SetTitle("Ratio of probability densities");
   placeholder0__1->GetYaxis()->SetDecimals();
   placeholder0__1->GetYaxis()->SetLabelFont(43);
   placeholder0__1->GetYaxis()->SetLabelOffset(0.015);
   placeholder0__1->GetYaxis()->SetLabelSize(19);
   placeholder0__1->GetYaxis()->SetTitleSize(26);
   placeholder0__1->GetYaxis()->SetTitleOffset(2);
   placeholder0__1->GetYaxis()->SetTitleFont(43);
   placeholder0__1->GetZaxis()->SetLabelFont(42);
   placeholder0__1->GetZaxis()->SetLabelSize(0.1);
   placeholder0__1->GetZaxis()->SetTitleSize(0.1);
   placeholder0__1->GetZaxis()->SetTitleOffset(1);
   placeholder0__1->GetZaxis()->SetTitleFont(42);
   placeholder0__1->Draw("axis");
   Double_t xAxis2[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder0__2 = new TH1D("placeholder0__2","Central Values",8, xAxis2);
   placeholder0__2->SetMinimum(0.1);
   placeholder0__2->SetMaximum(10);
   placeholder0__2->SetStats(0);
   placeholder0__2->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder0__2->GetXaxis()->SetLabelFont(43);
   placeholder0__2->GetXaxis()->SetLabelSize(0.035);
   placeholder0__2->GetXaxis()->SetTitleSize(0.035);
   placeholder0__2->GetXaxis()->SetTitleOffset(0.8);
   placeholder0__2->GetXaxis()->SetTitleFont(42);
   placeholder0__2->GetYaxis()->SetTitle("Ratio of probability densities");
   placeholder0__2->GetYaxis()->SetDecimals();
   placeholder0__2->GetYaxis()->SetLabelFont(43);
   placeholder0__2->GetYaxis()->SetLabelOffset(0.015);
   placeholder0__2->GetYaxis()->SetLabelSize(19);
   placeholder0__2->GetYaxis()->SetTitleSize(26);
   placeholder0__2->GetYaxis()->SetTitleOffset(2);
   placeholder0__2->GetYaxis()->SetTitleFont(43);
   placeholder0__2->GetZaxis()->SetLabelFont(42);
   placeholder0__2->GetZaxis()->SetLabelSize(0.1);
   placeholder0__2->GetZaxis()->SetTitleSize(0.1);
   placeholder0__2->GetZaxis()->SetTitleOffset(1);
   placeholder0__2->GetZaxis()->SetTitleFont(42);
   placeholder0__2->Draw("sameaxis");
   pad0->Modified();
   FinalSpectrum->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0.545,0.5,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(5,0.1,51.875,10.4125);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetLeftMargin(0);
   pad1->SetRightMargin(0.04);
   pad1->SetTopMargin(0.04);
   pad1->SetBottomMargin(0);
   pad1->SetFrameLineColor(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameLineColor(0);
   pad1->SetFrameBorderMode(0);
   Double_t xAxis3[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder1__3 = new TH1D("placeholder1__3","Central Values",8, xAxis3);
   placeholder1__3->SetMinimum(0.1);
   placeholder1__3->SetMaximum(10);
   placeholder1__3->SetStats(0);
   placeholder1__3->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder1__3->GetXaxis()->SetLabelFont(43);
   placeholder1__3->GetXaxis()->SetLabelSize(0.035);
   placeholder1__3->GetXaxis()->SetTitleSize(0.035);
   placeholder1__3->GetXaxis()->SetTitleOffset(0.8);
   placeholder1__3->GetXaxis()->SetTitleFont(42);
   placeholder1__3->GetYaxis()->SetTitle("Ratio of probability densities");
   placeholder1__3->GetYaxis()->SetDecimals();
   placeholder1__3->GetYaxis()->SetLabelFont(43);
   placeholder1__3->GetYaxis()->SetLabelOffset(0.015);
   placeholder1__3->GetYaxis()->SetLabelSize(19);
   placeholder1__3->GetYaxis()->SetTitleSize(26);
   placeholder1__3->GetYaxis()->SetTitleOffset(2);
   placeholder1__3->GetYaxis()->SetTitleFont(43);
   placeholder1__3->GetZaxis()->SetLabelFont(42);
   placeholder1__3->GetZaxis()->SetLabelSize(0.1);
   placeholder1__3->GetZaxis()->SetTitleSize(0.1);
   placeholder1__3->GetZaxis()->SetTitleOffset(1);
   placeholder1__3->GetZaxis()->SetTitleFont(42);
   placeholder1__3->Draw("axis");
   Double_t xAxis4[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder1__4 = new TH1D("placeholder1__4","Central Values",8, xAxis4);
   placeholder1__4->SetMinimum(0.1);
   placeholder1__4->SetMaximum(10);
   placeholder1__4->SetStats(0);
   placeholder1__4->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder1__4->GetXaxis()->SetLabelFont(43);
   placeholder1__4->GetXaxis()->SetLabelSize(0.035);
   placeholder1__4->GetXaxis()->SetTitleSize(0.035);
   placeholder1__4->GetXaxis()->SetTitleOffset(0.8);
   placeholder1__4->GetXaxis()->SetTitleFont(42);
   placeholder1__4->GetYaxis()->SetTitle("Ratio of probability densities");
   placeholder1__4->GetYaxis()->SetDecimals();
   placeholder1__4->GetYaxis()->SetLabelFont(43);
   placeholder1__4->GetYaxis()->SetLabelOffset(0.015);
   placeholder1__4->GetYaxis()->SetLabelSize(19);
   placeholder1__4->GetYaxis()->SetTitleSize(26);
   placeholder1__4->GetYaxis()->SetTitleOffset(2);
   placeholder1__4->GetYaxis()->SetTitleFont(43);
   placeholder1__4->GetZaxis()->SetLabelFont(42);
   placeholder1__4->GetZaxis()->SetLabelSize(0.1);
   placeholder1__4->GetZaxis()->SetTitleSize(0.1);
   placeholder1__4->GetZaxis()->SetTitleOffset(1);
   placeholder1__4->GetZaxis()->SetTitleFont(42);
   placeholder1__4->Draw("sameaxis");
   pad1->Modified();
   FinalSpectrum->cd();
  
// ------------>Primitives in pad: pad2
   TPad *pad2 = new TPad("pad2", "pad2",0,0.35,0.545,0.5);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-4.878049,0.7,50,1.3);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetGridy();
   pad2->SetTickx(1);
   pad2->SetTicky(1);
   pad2->SetLeftMargin(0.18);
   pad2->SetRightMargin(0);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0);
   pad2->SetFrameLineColor(0);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameLineColor(0);
   pad2->SetFrameBorderMode(0);
   Double_t xAxis5[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder2__5 = new TH1D("placeholder2__5","Central Values",8, xAxis5);
   placeholder2__5->SetMinimum(0.7);
   placeholder2__5->SetMaximum(1.3);
   placeholder2__5->SetStats(0);
   placeholder2__5->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder2__5->GetXaxis()->SetLabelFont(43);
   placeholder2__5->GetXaxis()->SetLabelSize(0.035);
   placeholder2__5->GetXaxis()->SetTitleSize(0.035);
   placeholder2__5->GetXaxis()->SetTitleOffset(0.8);
   placeholder2__5->GetXaxis()->SetTitleFont(42);
   placeholder2__5->GetYaxis()->SetTitle("MC/Data");
   placeholder2__5->GetYaxis()->SetDecimals();
   placeholder2__5->GetYaxis()->SetLabelFont(43);
   placeholder2__5->GetYaxis()->SetLabelOffset(0.015);
   placeholder2__5->GetYaxis()->SetLabelSize(19);
   placeholder2__5->GetYaxis()->SetTitleSize(26);
   placeholder2__5->GetYaxis()->SetTitleOffset(2);
   placeholder2__5->GetYaxis()->SetTitleFont(43);
   placeholder2__5->GetZaxis()->SetLabelFont(42);
   placeholder2__5->GetZaxis()->SetLabelSize(0.1);
   placeholder2__5->GetZaxis()->SetTitleSize(0.1);
   placeholder2__5->GetZaxis()->SetTitleOffset(1);
   placeholder2__5->GetZaxis()->SetTitleFont(42);
   placeholder2__5->Draw("axis");
   Double_t xAxis6[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder2__6 = new TH1D("placeholder2__6","Central Values",8, xAxis6);
   placeholder2__6->SetMinimum(0.7);
   placeholder2__6->SetMaximum(1.3);
   placeholder2__6->SetStats(0);
   placeholder2__6->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder2__6->GetXaxis()->SetLabelFont(43);
   placeholder2__6->GetXaxis()->SetLabelSize(0.035);
   placeholder2__6->GetXaxis()->SetTitleSize(0.035);
   placeholder2__6->GetXaxis()->SetTitleOffset(0.8);
   placeholder2__6->GetXaxis()->SetTitleFont(42);
   placeholder2__6->GetYaxis()->SetTitle("MC/Data");
   placeholder2__6->GetYaxis()->SetDecimals();
   placeholder2__6->GetYaxis()->SetLabelFont(43);
   placeholder2__6->GetYaxis()->SetLabelOffset(0.015);
   placeholder2__6->GetYaxis()->SetLabelSize(19);
   placeholder2__6->GetYaxis()->SetTitleSize(26);
   placeholder2__6->GetYaxis()->SetTitleOffset(2);
   placeholder2__6->GetYaxis()->SetTitleFont(43);
   placeholder2__6->GetZaxis()->SetLabelFont(42);
   placeholder2__6->GetZaxis()->SetLabelSize(0.1);
   placeholder2__6->GetZaxis()->SetTitleSize(0.1);
   placeholder2__6->GetZaxis()->SetTitleOffset(1);
   placeholder2__6->GetZaxis()->SetTitleFont(42);
   placeholder2__6->Draw("sameaxis");
   Double_t xAxis7[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder2__7 = new TH1D("placeholder2__7","Central Values",8, xAxis7);
   placeholder2__7->SetMinimum(0.7);
   placeholder2__7->SetMaximum(1.3);
   placeholder2__7->SetStats(0);
   placeholder2__7->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder2__7->GetXaxis()->SetLabelFont(43);
   placeholder2__7->GetXaxis()->SetLabelSize(0.035);
   placeholder2__7->GetXaxis()->SetTitleSize(0.035);
   placeholder2__7->GetXaxis()->SetTitleOffset(0.8);
   placeholder2__7->GetXaxis()->SetTitleFont(42);
   placeholder2__7->GetYaxis()->SetTitle("MC/Data");
   placeholder2__7->GetYaxis()->SetDecimals();
   placeholder2__7->GetYaxis()->SetLabelFont(43);
   placeholder2__7->GetYaxis()->SetLabelOffset(0.015);
   placeholder2__7->GetYaxis()->SetLabelSize(19);
   placeholder2__7->GetYaxis()->SetTitleSize(26);
   placeholder2__7->GetYaxis()->SetTitleOffset(2);
   placeholder2__7->GetYaxis()->SetTitleFont(43);
   placeholder2__7->GetZaxis()->SetLabelFont(42);
   placeholder2__7->GetZaxis()->SetLabelSize(0.1);
   placeholder2__7->GetZaxis()->SetTitleSize(0.1);
   placeholder2__7->GetZaxis()->SetTitleOffset(1);
   placeholder2__7->GetZaxis()->SetTitleFont(42);
   placeholder2__7->Draw("sameaxig");
   pad2->Modified();
   FinalSpectrum->cd();
  
// ------------>Primitives in pad: pad3
   TPad *pad3 = new TPad("pad3", "pad3",0.545,0.35,1,0.5);
   pad3->Draw();
   pad3->cd();
   pad3->Range(5,0.7,51.875,1.3);
   pad3->SetFillColor(0);
   pad3->SetBorderMode(0);
   pad3->SetBorderSize(2);
   pad3->SetGridy();
   pad3->SetTickx(1);
   pad3->SetTicky(1);
   pad3->SetLeftMargin(0);
   pad3->SetRightMargin(0.04);
   pad3->SetTopMargin(0);
   pad3->SetBottomMargin(0);
   pad3->SetFrameLineColor(0);
   pad3->SetFrameBorderMode(0);
   pad3->SetFrameLineColor(0);
   pad3->SetFrameBorderMode(0);
   Double_t xAxis8[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder3__8 = new TH1D("placeholder3__8","Central Values",8, xAxis8);
   placeholder3__8->SetMinimum(0.7);
   placeholder3__8->SetMaximum(1.3);
   placeholder3__8->SetStats(0);
   placeholder3__8->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder3__8->GetXaxis()->SetLabelFont(43);
   placeholder3__8->GetXaxis()->SetLabelSize(0.035);
   placeholder3__8->GetXaxis()->SetTitleSize(0.035);
   placeholder3__8->GetXaxis()->SetTitleOffset(0.8);
   placeholder3__8->GetXaxis()->SetTitleFont(42);
   placeholder3__8->GetYaxis()->SetTitle("MC/Data");
   placeholder3__8->GetYaxis()->SetDecimals();
   placeholder3__8->GetYaxis()->SetLabelFont(43);
   placeholder3__8->GetYaxis()->SetLabelOffset(0.015);
   placeholder3__8->GetYaxis()->SetLabelSize(19);
   placeholder3__8->GetYaxis()->SetTitleSize(26);
   placeholder3__8->GetYaxis()->SetTitleOffset(2);
   placeholder3__8->GetYaxis()->SetTitleFont(43);
   placeholder3__8->GetZaxis()->SetLabelFont(42);
   placeholder3__8->GetZaxis()->SetLabelSize(0.1);
   placeholder3__8->GetZaxis()->SetTitleSize(0.1);
   placeholder3__8->GetZaxis()->SetTitleOffset(1);
   placeholder3__8->GetZaxis()->SetTitleFont(42);
   placeholder3__8->Draw("axis");
   Double_t xAxis9[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder3__9 = new TH1D("placeholder3__9","Central Values",8, xAxis9);
   placeholder3__9->SetMinimum(0.7);
   placeholder3__9->SetMaximum(1.3);
   placeholder3__9->SetStats(0);
   placeholder3__9->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder3__9->GetXaxis()->SetLabelFont(43);
   placeholder3__9->GetXaxis()->SetLabelSize(0.035);
   placeholder3__9->GetXaxis()->SetTitleSize(0.035);
   placeholder3__9->GetXaxis()->SetTitleOffset(0.8);
   placeholder3__9->GetXaxis()->SetTitleFont(42);
   placeholder3__9->GetYaxis()->SetTitle("MC/Data");
   placeholder3__9->GetYaxis()->SetDecimals();
   placeholder3__9->GetYaxis()->SetLabelFont(43);
   placeholder3__9->GetYaxis()->SetLabelOffset(0.015);
   placeholder3__9->GetYaxis()->SetLabelSize(19);
   placeholder3__9->GetYaxis()->SetTitleSize(26);
   placeholder3__9->GetYaxis()->SetTitleOffset(2);
   placeholder3__9->GetYaxis()->SetTitleFont(43);
   placeholder3__9->GetZaxis()->SetLabelFont(42);
   placeholder3__9->GetZaxis()->SetLabelSize(0.1);
   placeholder3__9->GetZaxis()->SetTitleSize(0.1);
   placeholder3__9->GetZaxis()->SetTitleOffset(1);
   placeholder3__9->GetZaxis()->SetTitleFont(42);
   placeholder3__9->Draw("sameaxis");
   Double_t xAxis10[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder3__10 = new TH1D("placeholder3__10","Central Values",8, xAxis10);
   placeholder3__10->SetMinimum(0.7);
   placeholder3__10->SetMaximum(1.3);
   placeholder3__10->SetStats(0);
   placeholder3__10->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder3__10->GetXaxis()->SetLabelFont(43);
   placeholder3__10->GetXaxis()->SetLabelSize(0.035);
   placeholder3__10->GetXaxis()->SetTitleSize(0.035);
   placeholder3__10->GetXaxis()->SetTitleOffset(0.8);
   placeholder3__10->GetXaxis()->SetTitleFont(42);
   placeholder3__10->GetYaxis()->SetTitle("MC/Data");
   placeholder3__10->GetYaxis()->SetDecimals();
   placeholder3__10->GetYaxis()->SetLabelFont(43);
   placeholder3__10->GetYaxis()->SetLabelOffset(0.015);
   placeholder3__10->GetYaxis()->SetLabelSize(19);
   placeholder3__10->GetYaxis()->SetTitleSize(26);
   placeholder3__10->GetYaxis()->SetTitleOffset(2);
   placeholder3__10->GetYaxis()->SetTitleFont(43);
   placeholder3__10->GetZaxis()->SetLabelFont(42);
   placeholder3__10->GetZaxis()->SetLabelSize(0.1);
   placeholder3__10->GetZaxis()->SetTitleSize(0.1);
   placeholder3__10->GetZaxis()->SetTitleOffset(1);
   placeholder3__10->GetZaxis()->SetTitleFont(42);
   placeholder3__10->Draw("sameaxig");
   pad3->Modified();
   FinalSpectrum->cd();
  
// ------------>Primitives in pad: pad4
   TPad *pad4 = new TPad("pad4", "pad4",0,0.2,0.545,0.35);
   pad4->Draw();
   pad4->cd();
   pad4->Range(-4.878049,0.7,50,1.3);
   pad4->SetFillColor(0);
   pad4->SetBorderMode(0);
   pad4->SetBorderSize(2);
   pad4->SetGridy();
   pad4->SetTickx(1);
   pad4->SetTicky(1);
   pad4->SetLeftMargin(0.18);
   pad4->SetRightMargin(0);
   pad4->SetTopMargin(0);
   pad4->SetBottomMargin(0);
   pad4->SetFrameLineColor(0);
   pad4->SetFrameBorderMode(0);
   pad4->SetFrameLineColor(0);
   pad4->SetFrameBorderMode(0);
   Double_t xAxis11[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder4__11 = new TH1D("placeholder4__11","Central Values",8, xAxis11);
   placeholder4__11->SetMinimum(0.7);
   placeholder4__11->SetMaximum(1.3);
   placeholder4__11->SetStats(0);
   placeholder4__11->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder4__11->GetXaxis()->SetLabelFont(43);
   placeholder4__11->GetXaxis()->SetLabelSize(0.035);
   placeholder4__11->GetXaxis()->SetTitleSize(0.035);
   placeholder4__11->GetXaxis()->SetTitleOffset(0.8);
   placeholder4__11->GetXaxis()->SetTitleFont(42);
   placeholder4__11->GetYaxis()->SetTitle("MC/Data");
   placeholder4__11->GetYaxis()->SetDecimals();
   placeholder4__11->GetYaxis()->SetLabelFont(43);
   placeholder4__11->GetYaxis()->SetLabelOffset(0.015);
   placeholder4__11->GetYaxis()->SetLabelSize(19);
   placeholder4__11->GetYaxis()->SetTitleSize(26);
   placeholder4__11->GetYaxis()->SetTitleOffset(2);
   placeholder4__11->GetYaxis()->SetTitleFont(43);
   placeholder4__11->GetZaxis()->SetLabelFont(42);
   placeholder4__11->GetZaxis()->SetLabelSize(0.1);
   placeholder4__11->GetZaxis()->SetTitleSize(0.1);
   placeholder4__11->GetZaxis()->SetTitleOffset(1);
   placeholder4__11->GetZaxis()->SetTitleFont(42);
   placeholder4__11->Draw("axis");
   Double_t xAxis12[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder4__12 = new TH1D("placeholder4__12","Central Values",8, xAxis12);
   placeholder4__12->SetMinimum(0.7);
   placeholder4__12->SetMaximum(1.3);
   placeholder4__12->SetStats(0);
   placeholder4__12->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder4__12->GetXaxis()->SetLabelFont(43);
   placeholder4__12->GetXaxis()->SetLabelSize(0.035);
   placeholder4__12->GetXaxis()->SetTitleSize(0.035);
   placeholder4__12->GetXaxis()->SetTitleOffset(0.8);
   placeholder4__12->GetXaxis()->SetTitleFont(42);
   placeholder4__12->GetYaxis()->SetTitle("MC/Data");
   placeholder4__12->GetYaxis()->SetDecimals();
   placeholder4__12->GetYaxis()->SetLabelFont(43);
   placeholder4__12->GetYaxis()->SetLabelOffset(0.015);
   placeholder4__12->GetYaxis()->SetLabelSize(19);
   placeholder4__12->GetYaxis()->SetTitleSize(26);
   placeholder4__12->GetYaxis()->SetTitleOffset(2);
   placeholder4__12->GetYaxis()->SetTitleFont(43);
   placeholder4__12->GetZaxis()->SetLabelFont(42);
   placeholder4__12->GetZaxis()->SetLabelSize(0.1);
   placeholder4__12->GetZaxis()->SetTitleSize(0.1);
   placeholder4__12->GetZaxis()->SetTitleOffset(1);
   placeholder4__12->GetZaxis()->SetTitleFont(42);
   placeholder4__12->Draw("sameaxis");
   Double_t xAxis13[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder4__13 = new TH1D("placeholder4__13","Central Values",8, xAxis13);
   placeholder4__13->SetMinimum(0.7);
   placeholder4__13->SetMaximum(1.3);
   placeholder4__13->SetStats(0);
   placeholder4__13->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder4__13->GetXaxis()->SetLabelFont(43);
   placeholder4__13->GetXaxis()->SetLabelSize(0.035);
   placeholder4__13->GetXaxis()->SetTitleSize(0.035);
   placeholder4__13->GetXaxis()->SetTitleOffset(0.8);
   placeholder4__13->GetXaxis()->SetTitleFont(42);
   placeholder4__13->GetYaxis()->SetTitle("MC/Data");
   placeholder4__13->GetYaxis()->SetDecimals();
   placeholder4__13->GetYaxis()->SetLabelFont(43);
   placeholder4__13->GetYaxis()->SetLabelOffset(0.015);
   placeholder4__13->GetYaxis()->SetLabelSize(19);
   placeholder4__13->GetYaxis()->SetTitleSize(26);
   placeholder4__13->GetYaxis()->SetTitleOffset(2);
   placeholder4__13->GetYaxis()->SetTitleFont(43);
   placeholder4__13->GetZaxis()->SetLabelFont(42);
   placeholder4__13->GetZaxis()->SetLabelSize(0.1);
   placeholder4__13->GetZaxis()->SetTitleSize(0.1);
   placeholder4__13->GetZaxis()->SetTitleOffset(1);
   placeholder4__13->GetZaxis()->SetTitleFont(42);
   placeholder4__13->Draw("sameaxig");
   pad4->Modified();
   FinalSpectrum->cd();
  
// ------------>Primitives in pad: pad5
   TPad *pad5 = new TPad("pad5", "pad5",0.545,0.2,1,0.35);
   pad5->Draw();
   pad5->cd();
   pad5->Range(5,0.7,51.875,1.3);
   pad5->SetFillColor(0);
   pad5->SetBorderMode(0);
   pad5->SetBorderSize(2);
   pad5->SetGridy();
   pad5->SetTickx(1);
   pad5->SetTicky(1);
   pad5->SetLeftMargin(0);
   pad5->SetRightMargin(0.04);
   pad5->SetTopMargin(0);
   pad5->SetBottomMargin(0);
   pad5->SetFrameLineColor(0);
   pad5->SetFrameBorderMode(0);
   pad5->SetFrameLineColor(0);
   pad5->SetFrameBorderMode(0);
   Double_t xAxis14[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder5__14 = new TH1D("placeholder5__14","Central Values",8, xAxis14);
   placeholder5__14->SetMinimum(0.7);
   placeholder5__14->SetMaximum(1.3);
   placeholder5__14->SetStats(0);
   placeholder5__14->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder5__14->GetXaxis()->SetLabelFont(43);
   placeholder5__14->GetXaxis()->SetLabelSize(0.035);
   placeholder5__14->GetXaxis()->SetTitleSize(0.035);
   placeholder5__14->GetXaxis()->SetTitleOffset(0.8);
   placeholder5__14->GetXaxis()->SetTitleFont(42);
   placeholder5__14->GetYaxis()->SetTitle("MC/Data");
   placeholder5__14->GetYaxis()->SetDecimals();
   placeholder5__14->GetYaxis()->SetLabelFont(43);
   placeholder5__14->GetYaxis()->SetLabelOffset(0.015);
   placeholder5__14->GetYaxis()->SetLabelSize(19);
   placeholder5__14->GetYaxis()->SetTitleSize(26);
   placeholder5__14->GetYaxis()->SetTitleOffset(2);
   placeholder5__14->GetYaxis()->SetTitleFont(43);
   placeholder5__14->GetZaxis()->SetLabelFont(42);
   placeholder5__14->GetZaxis()->SetLabelSize(0.1);
   placeholder5__14->GetZaxis()->SetTitleSize(0.1);
   placeholder5__14->GetZaxis()->SetTitleOffset(1);
   placeholder5__14->GetZaxis()->SetTitleFont(42);
   placeholder5__14->Draw("axis");
   Double_t xAxis15[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder5__15 = new TH1D("placeholder5__15","Central Values",8, xAxis15);
   placeholder5__15->SetMinimum(0.7);
   placeholder5__15->SetMaximum(1.3);
   placeholder5__15->SetStats(0);
   placeholder5__15->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder5__15->GetXaxis()->SetLabelFont(43);
   placeholder5__15->GetXaxis()->SetLabelSize(0.035);
   placeholder5__15->GetXaxis()->SetTitleSize(0.035);
   placeholder5__15->GetXaxis()->SetTitleOffset(0.8);
   placeholder5__15->GetXaxis()->SetTitleFont(42);
   placeholder5__15->GetYaxis()->SetTitle("MC/Data");
   placeholder5__15->GetYaxis()->SetDecimals();
   placeholder5__15->GetYaxis()->SetLabelFont(43);
   placeholder5__15->GetYaxis()->SetLabelOffset(0.015);
   placeholder5__15->GetYaxis()->SetLabelSize(19);
   placeholder5__15->GetYaxis()->SetTitleSize(26);
   placeholder5__15->GetYaxis()->SetTitleOffset(2);
   placeholder5__15->GetYaxis()->SetTitleFont(43);
   placeholder5__15->GetZaxis()->SetLabelFont(42);
   placeholder5__15->GetZaxis()->SetLabelSize(0.1);
   placeholder5__15->GetZaxis()->SetTitleSize(0.1);
   placeholder5__15->GetZaxis()->SetTitleOffset(1);
   placeholder5__15->GetZaxis()->SetTitleFont(42);
   placeholder5__15->Draw("sameaxis");
   Double_t xAxis16[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder5__16 = new TH1D("placeholder5__16","Central Values",8, xAxis16);
   placeholder5__16->SetMinimum(0.7);
   placeholder5__16->SetMaximum(1.3);
   placeholder5__16->SetStats(0);
   placeholder5__16->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder5__16->GetXaxis()->SetLabelFont(43);
   placeholder5__16->GetXaxis()->SetLabelSize(0.035);
   placeholder5__16->GetXaxis()->SetTitleSize(0.035);
   placeholder5__16->GetXaxis()->SetTitleOffset(0.8);
   placeholder5__16->GetXaxis()->SetTitleFont(42);
   placeholder5__16->GetYaxis()->SetTitle("MC/Data");
   placeholder5__16->GetYaxis()->SetDecimals();
   placeholder5__16->GetYaxis()->SetLabelFont(43);
   placeholder5__16->GetYaxis()->SetLabelOffset(0.015);
   placeholder5__16->GetYaxis()->SetLabelSize(19);
   placeholder5__16->GetYaxis()->SetTitleSize(26);
   placeholder5__16->GetYaxis()->SetTitleOffset(2);
   placeholder5__16->GetYaxis()->SetTitleFont(43);
   placeholder5__16->GetZaxis()->SetLabelFont(42);
   placeholder5__16->GetZaxis()->SetLabelSize(0.1);
   placeholder5__16->GetZaxis()->SetTitleSize(0.1);
   placeholder5__16->GetZaxis()->SetTitleOffset(1);
   placeholder5__16->GetZaxis()->SetTitleFont(42);
   placeholder5__16->Draw("sameaxig");
   pad5->Modified();
   FinalSpectrum->cd();
  
// ------------>Primitives in pad: pad6
   TPad *pad6 = new TPad("pad6", "pad6",0,0,0.545,0.2);
   pad6->Draw();
   pad6->cd();
   pad6->Range(-4.878049,0.4780822,50,1.3);
   pad6->SetFillColor(0);
   pad6->SetBorderMode(0);
   pad6->SetBorderSize(2);
   pad6->SetGridy();
   pad6->SetTickx(1);
   pad6->SetTicky(1);
   pad6->SetLeftMargin(0.18);
   pad6->SetRightMargin(0);
   pad6->SetTopMargin(0);
   pad6->SetBottomMargin(0.27);
   pad6->SetFrameLineColor(0);
   pad6->SetFrameBorderMode(0);
   pad6->SetFrameLineColor(0);
   pad6->SetFrameBorderMode(0);
   Double_t xAxis17[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder6__17 = new TH1D("placeholder6__17","Central Values",8, xAxis17);
   placeholder6__17->SetMinimum(0.7);
   placeholder6__17->SetMaximum(1.3);
   placeholder6__17->SetStats(0);
   placeholder6__17->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder6__17->GetXaxis()->SetLabelFont(43);
   placeholder6__17->GetXaxis()->SetLabelSize(19);
   placeholder6__17->GetXaxis()->SetTitleSize(26);
   placeholder6__17->GetXaxis()->SetTitleOffset(0.8);
   placeholder6__17->GetXaxis()->SetTitleFont(42);
   placeholder6__17->GetYaxis()->SetTitle("MC/Data");
   placeholder6__17->GetYaxis()->SetDecimals();
   placeholder6__17->GetYaxis()->SetLabelFont(43);
   placeholder6__17->GetYaxis()->SetLabelOffset(0.015);
   placeholder6__17->GetYaxis()->SetLabelSize(19);
   placeholder6__17->GetYaxis()->SetTitleSize(26);
   placeholder6__17->GetYaxis()->SetTitleOffset(2);
   placeholder6__17->GetYaxis()->SetTitleFont(43);
   placeholder6__17->GetZaxis()->SetLabelFont(42);
   placeholder6__17->GetZaxis()->SetLabelSize(0.1);
   placeholder6__17->GetZaxis()->SetTitleSize(0.1);
   placeholder6__17->GetZaxis()->SetTitleOffset(1);
   placeholder6__17->GetZaxis()->SetTitleFont(42);
   placeholder6__17->Draw("axis");
   Double_t xAxis18[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder6__18 = new TH1D("placeholder6__18","Central Values",8, xAxis18);
   placeholder6__18->SetMinimum(0.7);
   placeholder6__18->SetMaximum(1.3);
   placeholder6__18->SetStats(0);
   placeholder6__18->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder6__18->GetXaxis()->SetLabelFont(43);
   placeholder6__18->GetXaxis()->SetLabelSize(19);
   placeholder6__18->GetXaxis()->SetTitleSize(26);
   placeholder6__18->GetXaxis()->SetTitleOffset(0.8);
   placeholder6__18->GetXaxis()->SetTitleFont(42);
   placeholder6__18->GetYaxis()->SetTitle("MC/Data");
   placeholder6__18->GetYaxis()->SetDecimals();
   placeholder6__18->GetYaxis()->SetLabelFont(43);
   placeholder6__18->GetYaxis()->SetLabelOffset(0.015);
   placeholder6__18->GetYaxis()->SetLabelSize(19);
   placeholder6__18->GetYaxis()->SetTitleSize(26);
   placeholder6__18->GetYaxis()->SetTitleOffset(2);
   placeholder6__18->GetYaxis()->SetTitleFont(43);
   placeholder6__18->GetZaxis()->SetLabelFont(42);
   placeholder6__18->GetZaxis()->SetLabelSize(0.1);
   placeholder6__18->GetZaxis()->SetTitleSize(0.1);
   placeholder6__18->GetZaxis()->SetTitleOffset(1);
   placeholder6__18->GetZaxis()->SetTitleFont(42);
   placeholder6__18->Draw("sameaxis");
   Double_t xAxis19[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder6__19 = new TH1D("placeholder6__19","Central Values",8, xAxis19);
   placeholder6__19->SetMinimum(0.7);
   placeholder6__19->SetMaximum(1.3);
   placeholder6__19->SetStats(0);
   placeholder6__19->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder6__19->GetXaxis()->SetLabelFont(43);
   placeholder6__19->GetXaxis()->SetLabelSize(19);
   placeholder6__19->GetXaxis()->SetTitleSize(26);
   placeholder6__19->GetXaxis()->SetTitleOffset(0.8);
   placeholder6__19->GetXaxis()->SetTitleFont(42);
   placeholder6__19->GetYaxis()->SetTitle("MC/Data");
   placeholder6__19->GetYaxis()->SetDecimals();
   placeholder6__19->GetYaxis()->SetLabelFont(43);
   placeholder6__19->GetYaxis()->SetLabelOffset(0.015);
   placeholder6__19->GetYaxis()->SetLabelSize(19);
   placeholder6__19->GetYaxis()->SetTitleSize(26);
   placeholder6__19->GetYaxis()->SetTitleOffset(2);
   placeholder6__19->GetYaxis()->SetTitleFont(43);
   placeholder6__19->GetZaxis()->SetLabelFont(42);
   placeholder6__19->GetZaxis()->SetLabelSize(0.1);
   placeholder6__19->GetZaxis()->SetTitleSize(0.1);
   placeholder6__19->GetZaxis()->SetTitleOffset(1);
   placeholder6__19->GetZaxis()->SetTitleFont(42);
   placeholder6__19->Draw("sameaxig");
   pad6->Modified();
   FinalSpectrum->cd();
  
// ------------>Primitives in pad: pad7
   TPad *pad7 = new TPad("pad7", "pad7",0.545,0,1,0.2);
   pad7->Draw();
   pad7->cd();
   pad7->Range(5,0.4780822,51.875,1.3);
   pad7->SetFillColor(0);
   pad7->SetBorderMode(0);
   pad7->SetBorderSize(2);
   pad7->SetGridy();
   pad7->SetTickx(1);
   pad7->SetTicky(1);
   pad7->SetLeftMargin(0);
   pad7->SetRightMargin(0.04);
   pad7->SetTopMargin(0);
   pad7->SetBottomMargin(0.27);
   pad7->SetFrameLineColor(0);
   pad7->SetFrameBorderMode(0);
   pad7->SetFrameLineColor(0);
   pad7->SetFrameBorderMode(0);
   Double_t xAxis20[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder7__20 = new TH1D("placeholder7__20","Central Values",8, xAxis20);
   placeholder7__20->SetMinimum(0.7);
   placeholder7__20->SetMaximum(1.3);
   placeholder7__20->SetStats(0);
   placeholder7__20->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder7__20->GetXaxis()->SetLabelFont(43);
   placeholder7__20->GetXaxis()->SetLabelSize(19);
   placeholder7__20->GetXaxis()->SetTitleSize(26);
   placeholder7__20->GetXaxis()->SetTitleOffset(0.8);
   placeholder7__20->GetXaxis()->SetTitleFont(42);
   placeholder7__20->GetYaxis()->SetTitle("MC/Data");
   placeholder7__20->GetYaxis()->SetDecimals();
   placeholder7__20->GetYaxis()->SetLabelFont(43);
   placeholder7__20->GetYaxis()->SetLabelOffset(0.015);
   placeholder7__20->GetYaxis()->SetLabelSize(19);
   placeholder7__20->GetYaxis()->SetTitleSize(26);
   placeholder7__20->GetYaxis()->SetTitleOffset(2);
   placeholder7__20->GetYaxis()->SetTitleFont(43);
   placeholder7__20->GetZaxis()->SetLabelFont(42);
   placeholder7__20->GetZaxis()->SetLabelSize(0.1);
   placeholder7__20->GetZaxis()->SetTitleSize(0.1);
   placeholder7__20->GetZaxis()->SetTitleOffset(1);
   placeholder7__20->GetZaxis()->SetTitleFont(42);
   placeholder7__20->Draw("axis");
   Double_t xAxis21[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder7__21 = new TH1D("placeholder7__21","Central Values",8, xAxis21);
   placeholder7__21->SetMinimum(0.7);
   placeholder7__21->SetMaximum(1.3);
   placeholder7__21->SetStats(0);
   placeholder7__21->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder7__21->GetXaxis()->SetLabelFont(43);
   placeholder7__21->GetXaxis()->SetLabelSize(19);
   placeholder7__21->GetXaxis()->SetTitleSize(26);
   placeholder7__21->GetXaxis()->SetTitleOffset(0.8);
   placeholder7__21->GetXaxis()->SetTitleFont(42);
   placeholder7__21->GetYaxis()->SetTitle("MC/Data");
   placeholder7__21->GetYaxis()->SetDecimals();
   placeholder7__21->GetYaxis()->SetLabelFont(43);
   placeholder7__21->GetYaxis()->SetLabelOffset(0.015);
   placeholder7__21->GetYaxis()->SetLabelSize(19);
   placeholder7__21->GetYaxis()->SetTitleSize(26);
   placeholder7__21->GetYaxis()->SetTitleOffset(2);
   placeholder7__21->GetYaxis()->SetTitleFont(43);
   placeholder7__21->GetZaxis()->SetLabelFont(42);
   placeholder7__21->GetZaxis()->SetLabelSize(0.1);
   placeholder7__21->GetZaxis()->SetTitleSize(0.1);
   placeholder7__21->GetZaxis()->SetTitleOffset(1);
   placeholder7__21->GetZaxis()->SetTitleFont(42);
   placeholder7__21->Draw("sameaxis");
   Double_t xAxis22[9] = {5, 6, 8, 10, 12, 14, 20, 30, 50}; 
   
   TH1D *placeholder7__22 = new TH1D("placeholder7__22","Central Values",8, xAxis22);
   placeholder7__22->SetMinimum(0.7);
   placeholder7__22->SetMaximum(1.3);
   placeholder7__22->SetStats(0);
   placeholder7__22->GetXaxis()->SetTitle("#it{p}_{T,ch jet} (GeV/#it{c})");
   placeholder7__22->GetXaxis()->SetLabelFont(43);
   placeholder7__22->GetXaxis()->SetLabelSize(19);
   placeholder7__22->GetXaxis()->SetTitleSize(26);
   placeholder7__22->GetXaxis()->SetTitleOffset(0.8);
   placeholder7__22->GetXaxis()->SetTitleFont(42);
   placeholder7__22->GetYaxis()->SetTitle("MC/Data");
   placeholder7__22->GetYaxis()->SetDecimals();
   placeholder7__22->GetYaxis()->SetLabelFont(43);
   placeholder7__22->GetYaxis()->SetLabelOffset(0.015);
   placeholder7__22->GetYaxis()->SetLabelSize(19);
   placeholder7__22->GetYaxis()->SetTitleSize(26);
   placeholder7__22->GetYaxis()->SetTitleOffset(2);
   placeholder7__22->GetYaxis()->SetTitleFont(43);
   placeholder7__22->GetZaxis()->SetLabelFont(42);
   placeholder7__22->GetZaxis()->SetLabelSize(0.1);
   placeholder7__22->GetZaxis()->SetTitleSize(0.1);
   placeholder7__22->GetZaxis()->SetTitleOffset(1);
   placeholder7__22->GetZaxis()->SetTitleFont(42);
   placeholder7__22->Draw("sameaxig");
   pad7->Modified();
   FinalSpectrum->cd();
   FinalSpectrum->Modified();
   FinalSpectrum->cd();
   FinalSpectrum->SetSelected(FinalSpectrum);
}
